
import java.util.*;
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author argif
 */
public class GuiCollection extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GuiCollection.class.getName());
    DefaultListModel<String> dlm;
    List<String> dataList = new ArrayList<>();
    Set<String> dataSet = new HashSet<>();
    Map<Integer, String> dataMap = new HashMap<>(); // Key: Index/ID, Value: Nama Item
    /**
     * Creates new form GuiCollection
     */
    public GuiCollection() {
        initComponents();
        this.dlm = new DefaultListModel<>();
        this.jListItem.setModel(dlm);
    }
    private void updateJumDataTersimpanList() {
        jLabelJumlahDataList.setText(
                "Data tersimpan = " + dataList.size()
        );
    }
    private void updateJumDataTersimpanSet() {
        jLabelJumlahDataSet.setText(
                "Data tersimpan = " + dataSet.size()
        );
    }
    private void updateJumDataTersimpanMap() {
        jLabelJumlahDataMap.setText(
                "Data tersimpan = " + dataMap.size()
        );
    }
    private void addItem(String namaItem) {
        dlm.addElement(namaItem);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListItem = new javax.swing.JList<>();
        jInsertToList = new javax.swing.JButton();
        jSaveList = new javax.swing.JButton();
        jLabelJumlahDataList = new javax.swing.JLabel();
        jLabelItemName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jUpdateButton = new javax.swing.JButton();
        jClearAllButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        jAddButton = new javax.swing.JButton();
        jSaveToSet = new javax.swing.JButton();
        jInsertToSet = new javax.swing.JButton();
        jLabelJumlahDataSet = new javax.swing.JLabel();
        jSaveToMap = new javax.swing.JButton();
        jLabelJumlahDataMap = new javax.swing.JLabel();
        jInsertToMap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListItem.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListItem);

        jInsertToList.setText("<- insert to List");
        jInsertToList.addActionListener(this::jInsertToListActionPerformed);

        jSaveList.setText("save to List ->");
        jSaveList.addActionListener(this::jSaveListActionPerformed);

        jLabelJumlahDataList.setText("Data tersimpan = 0");

        jLabelItemName.setText("item name :");

        jTextFieldName.addActionListener(this::jTextFieldNameActionPerformed);

        jUpdateButton.setText("update");
        jUpdateButton.addActionListener(this::jUpdateButtonActionPerformed);

        jClearAllButton.setText("clear all");
        jClearAllButton.addActionListener(this::jClearAllButtonActionPerformed);

        jDeleteButton.setText("delete");
        jDeleteButton.addActionListener(this::jDeleteButtonActionPerformed);

        jAddButton.setText("add");
        jAddButton.addActionListener(this::jAddButtonActionPerformed);

        jSaveToSet.setText("save to Set ->");
        jSaveToSet.addActionListener(this::jSaveToSetActionPerformed);

        jInsertToSet.setText("<- insert to Set");
        jInsertToSet.addActionListener(this::jInsertToSetActionPerformed);

        jLabelJumlahDataSet.setText("Data tersimpan = 0");

        jSaveToMap.setText("save to Map ->");
        jSaveToMap.addActionListener(this::jSaveToMapActionPerformed);

        jLabelJumlahDataMap.setText("Data tersimpan = 0");

        jInsertToMap.setText("<- insert to Map");
        jInsertToMap.addActionListener(this::jInsertToMapActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jClearAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelItemName)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jAddButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jUpdateButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSaveList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jInsertToList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSaveToSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jInsertToMap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSaveToMap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jInsertToSet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelJumlahDataMap, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelJumlahDataSet, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelJumlahDataList, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSaveList)
                            .addComponent(jLabelJumlahDataList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInsertToList)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSaveToSet)
                            .addComponent(jLabelJumlahDataSet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInsertToSet)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSaveToMap)
                            .addComponent(jLabelJumlahDataMap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jInsertToMap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelItemName)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jClearAllButton)
                    .addComponent(jDeleteButton)
                    .addComponent(jAddButton)
                    .addComponent(jUpdateButton))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInsertToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertToListActionPerformed
        // TODO add your handling code here:
        for (String item : dataList){
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jInsertToListActionPerformed

    private void jSaveListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveListActionPerformed
        // TODO add your handling code here:
        if (!dataList.isEmpty()) {
            dataList.clear();
        }
        for (int i = 0; i < dlm.getSize();i++) {
            dataList.add(dlm.getElementAt(i));
        }
        
        updateJumDataTersimpanList();
    }//GEN-LAST:event_jSaveListActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateButtonActionPerformed
        // TODO add your handling code here:4
        int index = jListItem.getSelectedIndex();
        String selected = jTextFieldName.getText();
        dlm.setElementAt(selected, index);
        jTextFieldName.setText("");
    }//GEN-LAST:event_jUpdateButtonActionPerformed

    private void jClearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearAllButtonActionPerformed
        // TODO add your handling code here:
        dlm.clear();
    }//GEN-LAST:event_jClearAllButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        // TODO add your handling code here:
        int index = jListItem.getSelectedIndex();
        dlm.removeElementAt(index);
        jTextFieldName.setText("");
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        // TODO add your handling code here:
        addItem(jTextFieldName.getText());
        jTextFieldName.setText("");
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jSaveToSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveToSetActionPerformed
        // TODO add your handling code here:
        if (!dataSet.isEmpty()) {
            dataSet.clear();
        }
        for (int i = 0; i < dlm.getSize();i++) {
            dataSet.add(dlm.getElementAt(i));
        }
        
        updateJumDataTersimpanSet();
    }//GEN-LAST:event_jSaveToSetActionPerformed

    private void jInsertToSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertToSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInsertToSetActionPerformed

    private void jSaveToMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveToMapActionPerformed
        // TODO add your handling code here:
        if (!dataMap.isEmpty()) {
            dataMap.clear();
        }
        for (int i = 0; i < dlm.getSize();i++) {
            dataList.add(dlm.getElementAt(i));
        }
        
        updateJumDataTersimpanList();
    }//GEN-LAST:event_jSaveToMapActionPerformed

    private void jInsertToMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertToMapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInsertToMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GuiCollection().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JButton jClearAllButton;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JButton jInsertToList;
    private javax.swing.JButton jInsertToMap;
    private javax.swing.JButton jInsertToSet;
    private javax.swing.JLabel jLabelItemName;
    private javax.swing.JLabel jLabelJumlahDataList;
    private javax.swing.JLabel jLabelJumlahDataMap;
    private javax.swing.JLabel jLabelJumlahDataSet;
    private javax.swing.JList<String> jListItem;
    private javax.swing.JButton jSaveList;
    private javax.swing.JButton jSaveToMap;
    private javax.swing.JButton jSaveToSet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JButton jUpdateButton;
    // End of variables declaration//GEN-END:variables
}
